version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5190:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production

  backend:
    build: ./backend
    ports:
      - "900:9000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/chatdb
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
